<a href="https://colab.research.google.com/github/showrin20/ML_DL_NLP_Learning-Path/blob/main/Numpy/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
!git clone https://github.com/showrin20/ML_DL_NLP_Learning-Path.git /content/ML_DL_NLP_Learning-Path


Cloning into '/content/ML_DL_NLP_Learning-Path'...
remote: Enumerating objects: 180, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 180 (delta 2), reused 0 (delta 0), pack-reused 174 (from 1)
Receiving objects: 100% (180/180), 87.44 KiB | 1.08 MiB/s, done.
Resolving deltas: 100% (78/78), done.


In [32]:
%cd /content/ML_DL_NLP_Learning-Path/Numpy


/content/ML_DL_NLP_Learning-Path/Numpy


In [33]:
!git config --global user.email "showrinrahman66@gmail.com"
!git config --global user.name "Showrin Rahman"

In [1]:
!pip install numpy

In [35]:
!cp /content/my_numpy_notebook.ipynb /content/ML_DL_NLP_Learning-Path/Numpy/ML.ipynb


cp: cannot stat '/content/my_numpy_notebook.ipynb': No such file or directory


In [3]:
import numpy as np

In [9]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
a

**Create**

In [5]:
r= np.random.rand(2,3,4)
r


array([[[0.53272285, 0.77740595, 0.43222755, 0.5756148 ],
        [0.25534828, 0.84102663, 0.40571609, 0.80571783],
        [0.15020077, 0.4409709 , 0.54938466, 0.65877853]],

       [[0.59511529, 0.31037263, 0.97397432, 0.84627911],
        [0.26393953, 0.9751538 , 0.70729763, 0.5983301 ],
        [0.96634679, 0.79955347, 0.71397923, 0.57865922]]])

In [7]:
a= np.ones((2,3,6))
a

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

# 🧾 NumPy Array Attributes


```python
import numpy as np

r = np.random.rand(2, 3, 4)
```

So `r` is a **3D array** with shape `(2, 3, 4)`.


## 🧱 1. `r.ndim` → Number of Dimensions

```python
print(r.ndim)   # Output: 3
```

### 🧠 Means:

* `1D` → vector
* `2D` → matrix
* `3D` → tensor / multi-channel image
* Higher → e.g. time series, batches, etc.


## 📐 2. `r.shape` → Tuple of Dimensions

```python
print(r.shape)  # Output: (2, 3, 4)
```

### 🧠 Means:

* 2 blocks
* each block has 3 rows
* each row has 4 elements

**`.shape`** is crucial for reshaping, slicing, and broadcasting.


## 🔢 3. `r.size` → Total Number of Elements

```python
print(r.size)   # Output: 24
```

### 🧠 Formula:

```python
2 × 3 × 4 = 24
```


## 💭 Bonus: More Attributes You Should Know

| Attribute    | What it Gives You                         |
| ------------ | ----------------------------------------- |
| `r.dtype`    | Data type (`float64`, `int32`, etc.)      |
| `r.itemsize` | Size in bytes of one element              |
| `r.nbytes`   | Total memory consumed (`size × itemsize`) |
| `r.T`        | Transpose (for 2D arrays)                 |

```python
print(r.dtype)       # float64
print(r.itemsize)    # 8  (for float64)
print(r.nbytes)      # 192 (24 × 8)
```



In [23]:
b= np.random.rand(3,3,4)
b


array([[[0.25253393, 0.53253362, 0.40904397, 0.80146625],
        [0.88785052, 0.43921481, 0.00453425, 0.15690748],
        [0.83902867, 0.30746409, 0.69376426, 0.46212766]],

       [[0.59118684, 0.78936562, 0.61756363, 0.87858585],
        [0.1981045 , 0.4726754 , 0.58716898, 0.67020793],
        [0.7162224 , 0.46150431, 0.79187169, 0.39638166]],

       [[0.3884249 , 0.83451625, 0.55925129, 0.15032578],
        [0.67611342, 0.04422372, 0.54407852, 0.63188717],
        [0.05588103, 0.79222411, 0.59413132, 0.31859642]]])

In [24]:
 b.ndim

3

In [25]:
b.shape

(3, 3, 4)

In [26]:
b.size

36

In [28]:
b.nbytes

288

In [29]:
b.dtype

dtype('float64')

In [30]:
b.itemsize

8